schema_version = "1.0.0"

id = "pivotier"
version = "2.0.0"
name = "Pivotier"
tagline = "Enhanced object alignment and pivot point management"
maintainer = "jhmorel <jhmorel11art@gmail.com>"
type = "add-on"

website = "https://github.com/jhmorel/Pivotier"
tags = ["Object", "Geometry", "Mesh", "3D View"]
blender_version_min = "3.6.5"
license = [
  "SPDX:GPL-3.0-or-later",
]
